# Generated by Django 5.0.7 on 2024-09-11 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='sub_cate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('img', models.ImageField(upload_to='image')),
                ('ram', models.IntegerField()),
                ('pmodel', models.CharField(max_length=20)),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product_master')),
            ],
        ),
    ]
